services:
  squid:
    image: sameersbn/squid:latest
    container_name: squid
    restart: unless-stopped
    ports:
      - "3128:3128"
    volumes:
      - ./Squid/cache:/var/spool/squid
      - ./Squid/conf/squid.conf:/etc/squid/squid.conf
    networks:
      - proxy_net

volumes:
  squid-cache:
  squid-logs:

networks:
  proxy_net:
    driver: bridge
