http_port 3128

cache_mem 64 MB
maximum_object_size_in_memory 512 KB
maximum_object_size 128 MB
cache_dir ufs /var/spool/squid 10 8 16

access_log /var/log/squid/access.log
cache_log /var/log/squid/cache.log

acl cache_sites url_regex -i ^https://github\.com/etcd-io/etcd/releases/
cache allow cache_sites
cache deny all

refresh_pattern ^https://github\.com/etcd-io/etcd/releases/ 1440 100% 4320
refresh_pattern . 0 20% 4320

http_access allow all
