<<<<<<< HEAD
get_host_os(HOST_OS)
=======
>>>>>>> 9b114aa382da2ca860f21271f9780439b8929d5c
set(MSI_ARCH_X86 "i386")
set(MSI_ARCH_X86_64 "x86_64")
set(MSI_ARCH_ARM64 "aarch64")


set(MSI_PACKAGE_EXT .msi)
set(MSI_PACKAGE_NAME msi)

set(MSIARCH_LIST_WINDOWS "${MSI_ARCH_X86};${MSI_ARCH_X86_64};${MSI_ARCH_ARM64}")
set(ALL_MSIARCH_LIST_WINDOWS ${MSIARCH_LIST_WINDOWS})


<<<<<<< HEAD
message(STATUS "RELEASE_DATE: ${RELEASE_DATE}")
=======
# message(STATUS "RELEASE_DATE: ${RELEASE_DATE}")
>>>>>>> 9b114aa382da2ca860f21271f9780439b8929d5c

execute_process(
    COMMAND bash -c "date -d '${RELEASE_DATE}' '+%a, %d %b %Y 00:00:00 +0000'"
    OUTPUT_VARIABLE RELEASE_DATE_MSI
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

<<<<<<< HEAD
message(STATUS "RELEASE_DATE_MSI: ${RELEASE_DATE_MSI}")

set(PACKAGE_ROOT_DIR "${CMAKE_BINARY_DIR}/${HOST_OS}/ins/${MSI_PACKAGE_NAME}/${APP_ARCH}/${APP_NAME}")
=======
# message(STATUS "RELEASE_DATE_MSI: ${RELEASE_DATE_MSI}")

set(PACKAGE_ROOT_DIR "${CMAKE_BINARY_DIR}/${OS_WINDOWS}/ins/${MSI_PACKAGE_NAME}/${APP_ARCH}/${APP_NAME}")
>>>>>>> 9b114aa382da2ca860f21271f9780439b8929d5c
set(MSI_ROOT_DIR "${CMAKE_BINARY_DIR}")
set(MSI_BUILD_ROOT_DIR "${MSI_ROOT_DIR}")
set(MSI_BUILD_CONFIG_DIR "${MSI_ROOT_DIR}/${APP_NAME}")
set(MSI_BUILD_PAYLOAD_DIR "${MSI_ROOT_DIR}/SOURCES")
set(MSI_BUILD_OUTPUT_DIR "${MSI_ROOT_DIR}/output")
set(MSI_BUILD_TEMP_DIR "${MSI_ROOT_DIR}/temp")


