# .github/workflows/branch-controls/check-branch-name.yml
name: Check PR Branch Naming

on:
  # pull_request:
  #   branches:
  #     - dev
  workflow_dispatch:

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        if: ${{ !startsWith(github.head_ref, 'feature/') }}
        run: |
          echo "Pull requests to 'dev' are only allowed from 'feature/**' branches."
          exit 1
