services:
  jenkins-agent-ubuntu:
    build:
      context: .
      dockerfile: Dockerfile-ubuntu-agent
    container_name: jenkins-agent-ubuntu
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /workspace
    command: >
      java -jar /workspace/agent.jar
      -url http://host.docker.internal:8080/
      -secret b2e068da37226505ceb6d39cf3b94f5b7708cf5c06d5e96e8f26bd5d83c960c9
      -name ubuntu
      -webSocket
      -workDir /workspace

  # jenkins-agent-ubuntu2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-ubuntu-agent
  #   container_name: jenkins-agent-ubuntu2
  #   restart: unless-stopped
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   working_dir: /workspace
  #   command: >
  #     java -jar /workspace/agent.jar
  #     -url http://host.docker.internal:8080/
  #     -secret 92214ba80a98a39ee68235e085e99a6d4b550da42f853396257b118f9787ce4e
  #     -name ubuntu2
  #     -webSocket
  #     -workDir /workspace
