services:
  bundle-service:
    url: http://192.168.118.47:8090

bundles:
  main:
    service: bundle-service
    resource: /bundle.tar.gz
    polling:
      min_delay_seconds: 10
      max_delay_seconds: 20

decision_logs:
  console: true

features:
  language_v1: true
