---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
# Sistemi güncelleyin
sudo dnf update -y

# nano editörünü kurun
sudo dnf install git -y

# nano editörünü kurun
sudo dnf install nano -y

# OpenJDK 21'i yükleyin
# sudo dnf install java-21-openjdk-devel -y

# Node.js 20 kurulum scriptini indirip çalıştırın
curl -fsSL https://rpm.nodesource.com/setup_20.x | sudo bash -

# Node.js'i yükleyin
sudo dnf install nodejs -y

# git-release-manager global kurulumu
sudo npm install -g git-release-manager@0.0.13

# CMake ve Make kurulumları
sudo dnf install cmake make -y

sudo dnf install gcc gcc-c++ -y



# Eski Go'yu sil
sudo rm -rf /usr/local/go

# Yeni sürümü indir
wget https://go.dev/dl/go1.22.3.linux-amd64.tar.gz

# /usr/local/go dizinine kur
sudo tar -C /usr/local -xzf go1.22.3.linux-amd64.tar.gz

# PATH ayarını tekrar kontrol et
echo 'export PATH=/usr/local/go/bin:$PATH' >> ~/.bashrc
source ~/.bashrc



# EPEL (Extra Packages for Enterprise Linux) deposunu etkinleştir
sudo dnf install epel-release -y

# Pandoc'u yükle
sudo dnf install pandoc -y
