set(PKG_ARCH_X86_64 "x86_64")
set(PKG_ARCH_ARM64 "aarch64")
set(PKG_ARCH_ALL "all")


set(PKG_PACKAGE_EXT .pkg)
set(PKG_PACKAGE_NAME pkg)

set(PKGARCH_LIST_MACOS "${PKG_ARCH_X86_64};${PKG_ARCH_ARM64}")
set(ALL_PKGARCH_LIST_MACOS ${PKGARCH_LIST_MACOS})
list(APPEND ALL_PKGARCH_LIST_MACOS ${PKG_ARCH_ALL})


# message(STATUS "RELEASE_DATE: ${RELEASE_DATE}")

execute_process(
    COMMAND bash -c "date -d '${RELEASE_DATE}' '+%a, %d %b %Y 00:00:00 +0000'"
    OUTPUT_VARIABLE RELEASE_DATE_PKG
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

# message(STATUS "RELEASE_DATE_PKG: ${RELEASE_DATE_PKG}")

set(PACKAGE_ROOT_DIR "${CMAKE_BINARY_DIR}/${OS_MACOS}/ins/${PKG_PACKAGE_NAME}/${APP_ARCH}/${APP_NAME}")
set(PKG_ROOT_DIR "${CMAKE_BINARY_DIR}")
set(PKG_BUILD_ROOT_DIR "${PKG_ROOT_DIR}")
set(PKG_BUILD_CONFIG_DIR "${PKG_ROOT_DIR}/${APP_NAME}")
set(PKG_BUILD_PAYLOAD_DIR "${PKG_ROOT_DIR}/SOURCES")
set(PKG_BUILD_OUTPUT_DIR "${PKG_ROOT_DIR}/output")
set(PKG_BUILD_TEMP_DIR "${PKG_ROOT_DIR}/temp")


