name: Build-Dev-Deb-Package

on:
  # push:
  #   tags:
  #     - "v*.*.*-dev.*"
  workflow_dispatch:

jobs:
  build-dev-deb-package:
    runs-on: ubuntu-latest

    # container:
    #   image: ahmetsoner/gh-build-image:latest
    #   options: --user root

    steps:
      # - name: Checkout source code
      #   uses: actions/checkout@v3

      # - name: Prepare version and tag
      #   run: |

      #     BUILD_VERSION=v1.0.0-dev.40
      #     make build.cmake.$BUILD_VERSION

      # make build.choco.package.all.configuration VERSION=$BUILD_VERSION # OK
      # make build.choco.package.all.payload VERSION=$BUILD_VERSION # FAIL
      # make build.choco.package.all.package VERSION=$BUILD_VERSION

      # make build.rpm.package.all.configuration VERSION=$BUILD_VERSION # OK
      # make build.rpm.package.all.payload VERSION=$BUILD_VERSION # OK
      # make build.rpm.package.all.package VERSION=$BUILD_VERSION # FAIL

      # make build.deb.package.all.configuration VERSION=$BUILD_VERSION # OK (PROJECT_MAINTAINER kapatıldı ama kıullanılması lazım)
      # make build.deb.package.all.payload VERSION=$BUILD_VERSION # OK
      # make build.deb.package.all.package VERSION=$BUILD_VERSION # OK (PROJECT_MAINTAINER olmadığı için hata veriyor sadece)

      # sudo make build.snap.package.setup VERSION=$BUILD_VERSION # Setup sudo ve snapcraft'tan dolayı hata veriyor
      # make build.snap.package.all.configuration VERSION=$BUILD_VERSION # OK
      # make build.snap.package.all.payload VERSION=$BUILD_VERSION # OK
      # make build.snap.package.all.package VERSION=$BUILD_VERSION

      # make build.brew.package.all.configuration VERSION=$BUILD_VERSION # OK

      - name: Setup Multipass
        run: sudo snap install multipass --classic

      - name: Launch Multipass VM
        run: |
          multipass launch --name snap-vm
          multipass exec snap-vm -- bash -c "
            sudo apt update &&
            sudo snap install snapcraft --classic &&
            cd /home/ubuntu/workspace &&
            # Your build commands here, e.g. snapcraft build
          "
