name: CI Build and Package Binaries

on:
  # push:
  #   tags:
  #     - "v*.*.*-dev.*"
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.version_and_tag.outputs.version }}
      base_version: ${{ steps.version_and_tag.outputs.base_version }}
      changelog_path: ${{ steps.version_and_tag.outputs.changelog_path }}
      artifact_path: ${{ steps.artifact.outputs.artifact_path }}
      html_output_dir: ${{ steps.docs.outputs.html_output_dir }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare Version and Tag
        id: version_and_tag
        uses: ./.github/actions/prepare-version
        with:
          channel: "dev"
          branch: "dev"
          email: "you@example.com"
          name: "Your Name"

      - name: Prepare artifact
        id: artifact
        uses: ./.github/actions/prepare-artifact
        with:
          version: ${{ steps.version_and_tag.outputs.version }}

      - name: Convert Markdown Docs to HTML Docs
        id: docs
        uses: ./.github/actions/crete-html-docs
        with:
          version: ${{ steps.version_and_tag.outputs.version }}

      - name: Generate release notes
        run: |
          VERSION=${{ steps.version_and_tag.outputs.version }}
          BASE_VERSION=${{ steps.version_and_tag.outputs.base_version }}
          CHANGELOG_PATH=${{ steps.version_and_tag.outputs.changelog_path }}
          grm changelog generate --from $BASE_VERSION-dev.1 --to $VERSION --environment dev --output $CHANGELOG_PATH

      - name: Create markdown file for checksums
        run: |
          echo "| Platform | Architecture | Type      | File Name | SHA-256 Checksum |" > $ARTIFACT_PATH/Checksums.md
          echo "|----------|--------------|-----------|-----------|------------------|" >> $ARTIFACT_PATH/Checksums.md
          echo "-------"
          echo $ARTIFACT_PATH
          ls -la $ARTIFACT_PATH
          echo "-------"

  build-matrix:
    runs-on: ubuntu-latest
    needs: prepare

    strategy:
      max-parallel: 1
      matrix:
        include:
          - os: linux
            arch: x86_64
            targets: ["binary"]
            binary: true
            archive: tar.gz
            # deb: true
            # rpm: true
          # - os: windows
          #   arch: x86_64
          #   binary: true
          #   archive: zip
          # - os: windows
          #   arch: arm
          #   binary: true
          #   archive: zip
          # - os: windows
          #   arch: arm64
          #   binary: true
          #   archive: zip
          # - os: linux
          #   arch: arm64
          #   binary: true
          #   archive: rar
          # - os: linux
          #   arch: arm64
          #   binary: true
          #   archive: 7z
          # - os: linux
          #   arch: all
          #   package: deb

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: print
        run: |

          echo "Version: ${{ needs.prepare.outputs.version }}"
          echo "Base Version: ${{ needs.prepare.outputs.base_version }}"
          echo "Changelog: ${{ needs.prepare.outputs.changelog_path }}"
          echo "Artifact Path: ${{ needs.prepare.outputs.artifact_path }}"

          echo "APPNAME=pars" >> $GITHUB_ENV


          echo "VERSION=${{ needs.prepare.outputs.version }}" >> $GITHUB_ENV
          echo "BASE_VERSION=${{ needs.prepare.outputs.base_version }}" >> $GITHUB_ENV
          echo "CHANGELOG_PATH=${{ needs.prepare.outputs.changelog_path }}" >> $GITHUB_ENV
          echo "ARTIFACT_PATH=${{ needs.prepare.outputs.artifact_path }}" >> $GITHUB_ENV
          echo "HTML_OUTPUT_DIR=${{ needs.prepare.outputs.html_output_dir }}" >> $GITHUB_ENV

          echo "Using OS: ${{ matrix.os }}"
          echo "Architecture: ${{ matrix.arch }}"
          echo "Artifact Binary: ${{ matrix.binary }}"
          echo "Artifact Archive: ${{ matrix.archive }}"

          if [ "${{ matrix.os }}" = "windows" ]; then
            EXT=".exe"
          else
            EXT=""
          fi

          echo "EXT=$EXT" >> $GITHUB_ENV

      - name: Build Binary
        if: matrix.binary
        # dist/$VERSION/windows/bin/x86_64/pars.exe'ye çıktı vermesi gerekirken .exe ext'i eklemiyor?
        # make build.binary.linux.arm64 gibi işlemlerin output pathini gösteren bir komut daha olmalı
        run: |

          VERSION=${{ needs.prepare.outputs.version }}
          make build.binary.${{matrix.os}}.${{matrix.arch}} VERSION=$VERSION

          BINARY_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/bin/${{matrix.arch}}
          BINARY_OUTPUT_PATH=$BINARY_OUTPUT_PATH_BASE/$APPNAME$EXT
          BINARY_CHCEKSUM_PATH=$BINARY_OUTPUT_PATH_BASE/checksum.txt

          # Calculate the checksum and store it in a variable
          BINARY_CHECKSUM=$(sha256sum "$BINARY_OUTPUT_PATH" | awk '{print $1}')
          echo "Checksum for $BINARY_OUTPUT_PATH: $BINARY_CHECKSUM"

          # Append the checksum and filepath to checksums.txt
          echo "$BINARY_CHECKSUM" > $BINARY_OUTPUT_PATH_BASE/checksum.txt



          echo "BINARY_OUTPUT_PATH_BASE=$BINARY_OUTPUT_PATH_BASE" >> $GITHUB_ENV
          echo "BINARY_OUTPUT_PATH=$BINARY_OUTPUT_PATH" >> $GITHUB_ENV
          echo "BINARY_CHCEKSUM_PATH=$BINARY_CHCEKSUM_PATH" >> $GITHUB_ENV

      - name: Create Artifact Binary
        if: matrix.binary
        run: |

          NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
          ORIGINAL_FILE_NAME="$APPNAME$EXT"

          # Copy the file to its new location with the new name
          echo "-------"
          echo $ARTIFACT_PATH
          ls -la $ARTIFACT_PATH
          echo "-------"
          cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$ARTIFACT_PATH/$NEW_BASE_NAME"

          CHECKSUM=$(cat "$BINARY_OUTPUT_PATH_BASE/checksum.txt")
          OS=${{matrix.os}}
          ARCH=${{matrix.arch}}
          TYPE=Binary
          FILENAME=$NEW_BASE_NAME

          # Add entry to Checksums.md
          echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> "$ARTIFACT_PATH/Checksums.md"

      # - name: Create Artifact Archive
      #   if: ${{ matrix.binary && matrix.archive }}
      #   run: |
      #     VERSION=${{ needs.prepare.outputs.version }}

      #     # Daha sonra burda file check yapılarak matrix.binary'den bağımsız ilerletilebilir olması sağlanacak
      #     if [ -f "$BINARY_OUTPUT_PATH" ] && [ -f "$BINARY_CHECKSUM_PATH" ]; then
      #         echo "Bin and Checksum files are present at specified paths."
      #     else
      #         echo "Required files do not exist. Skipping archive step."
      #     fi

      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}.bin.${{ matrix.archive }}
      #     BINARY_TEMP_PATH=dist/temp/$VERSION/$APPNAME-${{matrix.os}}-${{matrix.arch}}-${{ matrix.archive }}

      #     mkdir -p $BINARY_TEMP_PATH/bin
      #     cp $BINARY_OUTPUT_PATH "$BINARY_TEMP_PATH/bin/"

      #     mkdir -p $BINARY_TEMP_PATH/meta
      #     cp $BINARY_OUTPUT_PATH_BASE/checksum.txt "$BINARY_TEMP_PATH/meta/checksum.txt"

      #     # Copy docs into the temp directory hierarchically
      #     mkdir -p $BINARY_TEMP_PATH/docs
      #     cp -r $HTML_OUTPUT_DIR/ $BINARY_TEMP_PATH/docs/

      #     if [ "${{ matrix.archive }}" = "zip" ]; then
      #       (cd $BINARY_TEMP_PATH && zip -r "$NEW_BASE_NAME" .)
      #     elif [ "${{ matrix.archive }}" = "tar.gz" ]; then
      #       (cd $BINARY_TEMP_PATH && tar -czf "$NEW_BASE_NAME" . --warning=no-file-changed || true )
      #       if ! tar -tzf "$BINARY_TEMP_PATH/$NEW_BASE_NAME" > /dev/null; then
      #         echo "Error with archive: Unable to list contents for validation."
      #       fi
      #     elif [ "${{ matrix.archive }}" = "7z" ]; then
      #       (cd $BINARY_TEMP_PATH && 7z a "$NEW_BASE_NAME" *)
      #     elif [ "${{ matrix.archive }}" = "rar" ]; then
      #       ( cd $BINARY_TEMP_PATH && rar a $NEW_BASE_NAME * )
      #     fi

      #     cp "$BINARY_TEMP_PATH/$NEW_BASE_NAME" "$ARTIFACT_PATH/$NEW_BASE_NAME"

      #     # Calculate the checksum and store it in a variable
      #     BINARY_PACKAGE_CHECKSUM=$(sha256sum "$BINARY_TEMP_PATH/$NEW_BASE_NAME" | awk '{print $1}')

      #     # Append the checksum and filepath to checksums.txt
      #     echo "$BINARY_PACKAGE_CHECKSUM" > $BINARY_TEMP_PATH/checksum.txt

      #     CHECKSUM=$(cat $BINARY_TEMP_PATH/checksum.txt)
      #     OS=${{matrix.os}}
      #     ARCH=${{matrix.arch}}
      #     TYPE=Archieve
      #     FILENAME=$NEW_BASE_NAME

      #     echo "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |" >> $ARTIFACT_PATH/Checksums.md

      # - name: Build .deb Package
      #   if: ${{ matrix.os == 'linux' && matrix.deb }}
      #   run: |

      #     VERSION=${{ needs.prepare.outputs.version }}
      #     PCKG_PATH=usr/bin/pars

      #     PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/deb/${{matrix.arch}}/$APPNAME
      #     PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH

      #     mkdir -p $PACKAGE_BINARY_OUTPUT_PATH

      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
      #     ORIGINAL_FILE_NAME="$APPNAME$EXT"

      #     cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"

      #     make build.deb.package.${{matrix.arch}}.configuration VERSION=$VERSION
      #     make build.deb.package.${{matrix.arch}}.payload VERSION=$VERSION
      #     make build.deb.package.${{matrix.arch}}.package VERSION=$VERSION

      # - name: Build .rpm Package
      #   if: ${{ matrix.os == 'linux' && matrix.rpm }}
      #   run: |

      #     VERSION=${{ needs.prepare.outputs.version }}
      #     PCKG_PATH=usr/bin/pars

      #     PACKAGE_OUTPUT_PATH_BASE=dist/$VERSION/${{matrix.os}}/pkg/deb/${{matrix.arch}}/$APPNAME
      #     PACKAGE_BINARY_OUTPUT_PATH=$PACKAGE_OUTPUT_PATH_BASE/$PCKG_PATH

      #     mkdir -p $PACKAGE_BINARY_OUTPUT_PATH

      #     NEW_BASE_NAME=$APPNAME-${{matrix.os}}-${{matrix.arch}}$EXT
      #     ORIGINAL_FILE_NAME="$APPNAME$EXT"

      #     cp "$BINARY_OUTPUT_PATH_BASE/$ORIGINAL_FILE_NAME" "$PACKAGE_BINARY_OUTPUT_PATH"

      #     make build.deb.package.${{matrix.arch}}.configuration VERSION=$VERSION
      #     make build.deb.package.${{matrix.arch}}.payload VERSION=$VERSION
      #     make build.deb.package.${{matrix.arch}}.package VERSION=$VERSION
