# https://chatgpt.com/c/67e52d1f-fd1c-8004-9693-e4c3cc115836

name: Tag-Dev

on:
  workflow_dispatch:

jobs:
  hellow:
    runs-on: windows-latest


    steps:
      - name: hello windows runner
        uses: actions/checkout@v3

      - name: Hello
        run: |
          Write-Host "Hello windows runner"
