# https://chatgpt.com/c/67e52d1f-fd1c-8004-9693-e4c3cc115836

name: Tag-Dev

on:
  workflow_dispatch:

jobs:
  hellow:
    runs-on: windows-latest


    strategy:
      max-parallel: 1
      matrix:
        include:
          # # - os: linux
          # #   arch: x86
          # #   targets: ["binary"]
          # #   binary: true
          # #   archive: tar.gz
          # #   deb: false
          # #   rpm: true
          # - os: linux
          #   arch: x86_64
          #   targets: ["binary"]
          #   binary: true
          #   archive: tar.gz
          #   deb: true
          #   rpm: false
          # # - os: linux
          # #   arch: arm
          # #   targets: ["binary"]
          # #   binary: true
          # #   archive: tar.gz
          # #   deb: false
          # #   rpm: true
          # - os: linux
          #   arch: arm64
          #   targets: ["binary"]
          #   binary: true
          #   archive: tar.gz
          #   deb: true
          #   rpm: false
          # # - os: windows
          # #   arch: x86
          # #   binary: true
          # #   archive: zip
          - os: windows
            arch: x86_64
            # binary: true
            # archive: zip
            msi: true
          # # - os: windows
          # #   arch: arm
          # #   binary: true
          # #   archive: zip
          # - os: windows
          #   arch: arm64
          #   binary: true
          #   archive: zip

    steps:
      - name: hello windows runner
        uses: actions/checkout@v3

      - name: Build Binary
        if: matrix.binary
        run: |
          $VERSION = "v1.0.0-dev.40"
          $EXT = ".exe"
          $APPNAME = "pars"

          make build.cmake.$VERSION
          make build.binary.${{matrix.os}}.${{matrix.arch}} VERSION=$VERSION

          $BINARY_OUTPUT_PATH_BASE = "dist/$VERSION/${{ matrix.os }}/bin/${{ matrix.arch }}"
          $BINARY_OUTPUT_PATH = "$BINARY_OUTPUT_PATH_BASE/$APPNAME$EXT"
          $BINARY_CHECKSUM_PATH = "$BINARY_OUTPUT_PATH_BASE/checksum.txt"

          # Checksum hesapla
          $BINARY_CHECKSUM = (Get-FileHash -Algorithm SHA256 $BINARY_OUTPUT_PATH).Hash
          Write-Output "Checksum for ${BINARY_OUTPUT_PATH}: ${BINARY_CHECKSUM}"

          # checksum.txt dosyasına yaz
          Set-Content -Path $BINARY_CHECKSUM_PATH -Value $BINARY_CHECKSUM

          # Ortam değişkenlerini ayarla
          "BINARY_OUTPUT_PATH_BASE=$BINARY_OUTPUT_PATH_BASE" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV
          "BINARY_OUTPUT_PATH=$BINARY_OUTPUT_PATH" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV
          "BINARY_CHECKSUM_PATH=$BINARY_CHECKSUM_PATH" | Out-File -Append -Encoding utf8 $env:GITHUB_ENV

      - name: Create Artifact Binary
        if: matrix.binary
        run: |
          $VERSION = "v1.0.0-dev.40"
          $EXT = ".exe"
          $APPNAME = "pars"
          $ARTIFACT_PATH = "dist/artifacts/$VERSION"
          
          $BINARY_OUTPUT_PATH_BASE = $env:BINARY_OUTPUT_PATH_BASE

          $NEW_BASE_NAME = "$APPNAME-${{ matrix.os }}-${{ matrix.arch }}$EXT"
          $ORIGINAL_FILE_NAME = "$APPNAME$EXT"

          # Ensure the target directory exists
          New-Item -ItemType Directory -Path $ARTIFACT_PATH -Force | Out-Null

          # Copy the binary
          Copy-Item "$BINARY_OUTPUT_PATH_BASE\$ORIGINAL_FILE_NAME" "$ARTIFACT_PATH\$NEW_BASE_NAME"

          # Read checksum
          $CHECKSUM = Get-Content "$BINARY_OUTPUT_PATH_BASE\checksum.txt"

          # Metadata
          $OS = "${{ matrix.os }}"
          $ARCH = "${{ matrix.arch }}"
          $TYPE = "Binary"
          $FILENAME = $NEW_BASE_NAME

          # Add entry to Checksums.md
          Add-Content -Path "$ARTIFACT_PATH\Checksums.md" -Value "| $OS | $ARCH | $TYPE | $FILENAME | $CHECKSUM |"

      - name: Create Artifact Archive
        if: ${{ matrix.binary && matrix.archive }}
        run: |
          $VERSION = "v1.0.0-dev.40"
          $EXT = ".exe"
          $APPNAME = "pars"
          $ARTIFACT_PATH = "dist/artifacts/$VERSION"

          $OS = "${{ matrix.os }}"
          $ARCH = "${{ matrix.arch }}"
          $ARCHIVE = "${{ matrix.archive }}"

          $NEW_BASE_NAME = "$APPNAME-$OS-$ARCH.bin.$ARCHIVE"
          $BINARY_TEMP_PATH = "dist/temp/$VERSION/$APPNAME-$OS-$ARCH-$ARCHIVE"

          # Ortam değişkenlerinden yol al
          $BINARY_OUTPUT_PATH = $env:BINARY_OUTPUT_PATH
          $BINARY_OUTPUT_PATH_BASE = $env:BINARY_OUTPUT_PATH_BASE
          # $HTML_OUTPUT_DIR = $env:HTML_OUTPUT_DIR

          if ((Test-Path $BINARY_OUTPUT_PATH) -and (Test-Path $env:BINARY_CHECKSUM_PATH)) {
            Write-Host "Bin and Checksum files are present at specified paths."
          } else {
            Write-Host "Required files do not exist. Skipping archive step."
            exit 0
          }

          # Dizini hazırla ve dosyaları kopyala
          New-Item -ItemType Directory -Force -Path "$BINARY_TEMP_PATH/bin" | Out-Null
          Copy-Item $BINARY_OUTPUT_PATH -Destination "$BINARY_TEMP_PATH/bin/" -Force

          New-Item -ItemType Directory -Force -Path "$BINARY_TEMP_PATH/meta" | Out-Null
          Copy-Item "$BINARY_OUTPUT_PATH_BASE/checksum.txt" "$BINARY_TEMP_PATH/meta/checksum.txt" -Force

          New-Item -ItemType Directory -Force -Path "$BINARY_TEMP_PATH/docs" | Out-Null
          # Copy-Item "$HTML_OUTPUT_DIR\*" "$BINARY_TEMP_PATH/docs/" -Recurse -Force

          # Arşiv oluştur
          Push-Location $BINARY_TEMP_PATH
          if ($ARCHIVE -eq "zip") {
            Compress-Archive -Path * -DestinationPath "$NEW_BASE_NAME"
          }
          elseif ($ARCHIVE -eq "tar.gz") {
            tar -czf "$NEW_BASE_NAME" * --force-local
          }
          elseif ($ARCHIVE -eq "7z") {
            & 7z a "$NEW_BASE_NAME" * | Out-Null
          }
          elseif ($ARCHIVE -eq "rar") {
            & rar a "$NEW_BASE_NAME" * | Out-Null
          }
          Pop-Location

          Copy-Item "$BINARY_TEMP_PATH\$NEW_BASE_NAME" "$ARTIFACT_PATH\$NEW_BASE_NAME" -Force

          # SHA256 checksum hesapla
          $BINARY_PACKAGE_CHECKSUM = (Get-FileHash "$BINARY_TEMP_PATH\$NEW_BASE_NAME" -Algorithm SHA256).Hash
          Set-Content -Path "$BINARY_TEMP_PATH/checksum.txt" -Value $BINARY_PACKAGE_CHECKSUM

          # Checksums.md dosyasına ekle
          $line = "| $OS | $ARCH | Archive | $NEW_BASE_NAME | $BINARY_PACKAGE_CHECKSUM |"
          Add-Content -Path "$ARTIFACT_PATH/Checksums.md" -Value $line

      - name: Build .msi Installer
        if: ${{ matrix.os == 'windows' && matrix.msi }}
        run: |
          $VERSION = "v1.0.0-dev.40"
          $EXT = ".exe"
          $APPNAME = "pars"
          $ARTIFACT_PATH = "dist/artifacts/$VERSION"

          make build.msi.package.${{matrix.arch}}.configuration VERSION=$VERSION
          make build.msi.package.${{matrix.arch}}.payload VERSION=$VERSION
          make build.msi.package.${{matrix.arch}}.package VERSION=$VERSION



          # MSI mimari belirleme
          $Matrix_Arch = "${{matrix.arch}}"
          $MSI_ARCH = ""
          switch ($Matrix_Arch) {
              "x86"     { $MSI_ARCH = "i386" }
              "x86_64"  { $MSI_ARCH = "x86_64" }
              "arm"     { $MSI_ARCH = "arm" }
              "arm64"   { $MSI_ARCH = "aarch64" }
              default {
                  Write-Error "Unsupported architecture: $Matrix_Arch"
                  exit 1
              }
          }

          # # Dosya yolları
          # $MSI_OUTPUT_PATH_BASE = Join-Path $env:PACKAGE_OUTPUT_PATH_BASE "output"
          # $MSI_CHECKSUM_PATH = Join-Path $MSI_OUTPUT_PATH_BASE "checksum.txt"

          # # Versiyonun başındaki 'v' karakterini kaldır
          # $PLAIN_VERSION = $env:VERSION -replace "^v", ""

          # # MSI dosya yolu
          # $MSI_OUTPUT_PATH = Join-Path $MSI_OUTPUT_PATH_BASE "pars_${PLAIN_VERSION}_${MSI_ARCH}.msi"

          # # SHA256 checksum hesapla
          # $MSI_CHECKSUM = Get-FileHash -Path $MSI_OUTPUT_PATH -Algorithm SHA256 | Select-Object -ExpandProperty Hash
          # Write-Host "Checksum for $MSI_OUTPUT_PATH: $MSI_CHECKSUM"

          # # Checksum'u dosyaya yaz
          # $MSI_CHECKSUM | Out-File -Encoding ascii -FilePath $MSI_CHECKSUM_PATH

          # # GitHub ortam değişkenlerine yaz
          # @(
          #     "MSI_OUTPUT_PATH=$MSI_OUTPUT_PATH"
          #     "MSI_OUTPUT_PATH_BASE=$MSI_OUTPUT_PATH_BASE"
          #     "MSI_CHECKSUM_PATH=$MSI_CHECKSUM_PATH"
          # ) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Save files for later jobs
        run: |
          $WORKFLOW_DIR = "C:\Users\Administrator\Desktop\AS\prj\pars\temp\workflow"

          # Remove the directory if it exists
          if (Test-Path $WORKFLOW_DIR) {
            Remove-Item -Recurse -Force $WORKFLOW_DIR
          }

          # Recreate the directory
          New-Item -ItemType Directory -Path $WORKFLOW_DIR -Force | Out-Null

          # Copy all files and folders from current directory to workflow directory
          Copy-Item -Path .\* -Destination $WORKFLOW_DIR -Recurse -Force